import { appendFileSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { AgentProvider, RawEvent, RunHandle, StartInput } from './types.ts'

// Fallback provider used when the real Droid CLI isn't installed/logged in.
// It streams realistic events AND makes a genuine file edit in the repo so the
// git diff + review flow is fully exercisable without Factory credentials.
export const simulatedProvider: AgentProvider = {
  id: 'simulated',
  displayName: 'Simulated Droid (no CLI)',

  async detect() {
    return { available: true, detail: 'Built-in simulation — install `droid` for the real engine' }
  },

  run({ repoPath, prompt }: StartInput, onEvent: (e: RawEvent) => void): RunHandle {
    const timers: ReturnType<typeof setTimeout>[] = []
    let cancelled = false
    const slug = prompt.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 40) || 'task'

    const step = (delay: number, fn: () => void) => {
      timers.push(setTimeout(() => !cancelled && fn(), delay))
    }

    step(150, () => onEvent({ kind: 'status', title: 'Droid started', body: `Working in ${repoPath}` }))
    step(700, () =>
      onEvent({
        kind: 'plan',
        title: 'Planned the work',
        body: `Break "${prompt}" into: inspect the repo, apply a focused edit, and record the change.`,
      }),
    )
    step(1500, () =>
      onEvent({ kind: 'search', title: 'Explored the codebase', body: 'Scanned project files to match existing conventions.' }),
    )
    step(2400, () => {
      // Make a real, safe change so there's something to review.
      try {
        const docDir = join(repoPath, 'droid')
        mkdirSync(docDir, { recursive: true })
        const docPath = join(docDir, `${slug}.md`)
        writeFileSync(
          docPath,
          `# ${prompt}\n\nGenerated by DROID (simulated provider).\n\n- [x] Inspected repo\n- [x] Applied change\n- [x] Recorded note\n`,
        )
        appendFileSync(
          join(repoPath, 'CHANGELOG.md'),
          `\n## ${new Date().toISOString().slice(0, 10)} — ${prompt}\n\nHandled by DROID.\n`,
        )
        onEvent({ kind: 'edit', title: 'Edited files', body: `Created droid/${slug}.md and updated CHANGELOG.md`, file: `droid/${slug}.md` })
      } catch (e) {
        onEvent({ kind: 'error', title: 'Edit failed', body: String(e) })
      }
    })
    step(3300, () =>
      onEvent({ kind: 'command', title: 'Ran checks', body: '$ npm test\n\n✓ 12 passed, 0 failed' }),
    )
    step(4000, () =>
      onEvent({
        kind: 'message',
        title: 'Summary',
        body: `Done: applied "${prompt}". Review the changed files on the right, then Accept or Revert.`,
      }),
    )
    step(4300, () => onEvent({ kind: 'completed', title: 'Droid completed' }))

    return {
      cancel: () => {
        cancelled = true
        timers.forEach(clearTimeout)
      },
    }
  },
}
